import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { CollectionsView } from "@/components/collections-view";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/state-provider";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { db } from "@/database/database";
import { collections as collectionsSchema } from "@/database/schema";
import { asc } from "drizzle-orm";
import CollectionsProvider from "@/components/collections-provider";
import { QCProvider } from "@/components/query-client-provider";
import { CollectionsPicker } from "@/components/collections-picker";
import { CommandMenu } from "@/components/command-menu";
import { CreateCollectionForm } from "@/components/collection-form";
import { CreateLinkForm } from "@/components/link-form";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const collections = await db
    .select()
    .from(collectionsSchema)
    .orderBy(asc(collectionsSchema.order));

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen dark:bg-neutral-950">
        <Providers>
          <QCProvider>
            <CollectionsProvider collections={collections}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
              >
                <main className="relative flex min-h-screen flex-col">
                  <header className="sticky top-0 z-10 w-full border-b backdrop-blur dark:border-neutral-800">
                    <div className="container flex h-16 max-w-5xl flex-row items-center">
                      <CollectionsPicker />
                      <div className="ml-auto mt-0">
                        <ThemeToggle />
                      </div>
                    </div>
                  </header>
                  <div className="mx-auto h-full w-full max-w-5xl gap-4 px-8 pt-8">
                    {children}
                  </div>
                </main>
                <CommandMenu />
                <CreateLinkForm />
                <CreateCollectionForm />
                <Toaster position="bottom-center" />
              </ThemeProvider>
            </CollectionsProvider>
          </QCProvider>
        </Providers>
      </body>
    </html>
  );
}
